editor:
  preview: false
publish_mode: editorial_workflow
site_url: https://yarkov.tech
display_url: https://yarkov.tech
i18n:
  locales: [ru, en]
  default_locale: ru
  structure: multiple_folders
locale: en
backend:
  name: github
  repo: sergeyyarkov/yarkov.tech
  branch: main
media_folder: public/media
public_folder: "/media"
collections:
  - name: articles
    label: Публикации
    label_singular: публикацию
    description: Технические статьи, туториалы и различные справочные материалы которые связаны с IT тематикой
    folder: src/content/blog
    slug: "{{slug}}"
    create: true
    delete: true
    i18n: true
    fields:
      - name: coverImage
        widget: image
        label: Постер
        required: false
        i18n: true
      - name: draft
        label: В черновике
        widget: boolean
        hint: Опубликована ли статья
        i18n: true
        required: false
      - name: author
        widget: relation
        value_field: "{{firstName}} {{lastName}}"
        search_fields:
          - firstName
          - lastName
        collection: authors
        label: Автор
        i18n: true
      - name: title
        widget: string
        label: Заголовок
        i18n: true
      - name: description
        widget: string
        label: Описание
        i18n: true
      - name: tags
        widget: relation
        label: Тэги
        collection: tags
        multiple: true
        value_field: title
        search_fields:
          - title
        i18n: true
      - name: pubDate
        widget: datetime
        label: Дата публикации
        picker_utc: true
        i18n: true
      - name: updatedDate
        widget: datetime
        label: Дата обновления
        picker_utc: true
        i18n: true
      - name: body
        widget: markdown
        label: Содержание
        i18n: true
  - name: tags
    label: Тэги
    label_singular: тэг
    description: Используются для тегирования контента
    folder: src/content/tags
    create: true
    delete: true
    fields:
      - name: title
        widget: string
        label: Название
        required: true
  - name: authors
    label: Авторы
    label_singular: автора
    description: На странице статьи отображается имя автора
    slug: "{{firstName}}-{{lastName}}"
    folder: src/content/authors
    create: true
    delete: true
    i18n: true
    fields:
      - label: Имя
        name: firstName
        widget: string
        required: true
        i18n: true
      - label: Фамилия
        name: lastName
        widget: string
        required: true
        i18n: true
      - label: Об авторе
        name: body
        widget: markdown
        required: false
        i18n: true
  - name: projects
    label: Проекты
    label_singular: проект
    description: Основные проекты, которые были разработаны в выложены в открытый
      доступ
    folder: src/content/projects
    create: true
    delete: true
    i18n: true
    fields:
      - name: icon
        label: Иконка
        widget: string
        required: true
        i18n: true
      - name: title
        label: Название
        widget: string
        required: true
        i18n: true
      - name: year
        label: В каком году разработал
        widget: number
        required: true
        i18n: true
      - name: description
        label: Описание
        widget: string
        required: true
        i18n: true
      - name: sourceUrl
        label: Ссылка на исходник
        widget: string
        required: true
        i18n: true
      - name: demoUrl
        label: Ссылка на демонстрацию
        widget: string
        required: false
        i18n: true
      - name: articleUrl
        label: Ссылка на статью
        widget: string
        required: false
        i18n: true
  - name: skills
    label: Навыки
    label_singular: навык
    folder: src/content/skills
    create: true
    delete: true
    description: Навыки отображаются на странице Обо мне
    i18n: true
    fields:
      - name: title
        label: Категория
        widget: string
        required: true
        i18n: true
      - name: list
        label: Записи
        required: true
        widget: list
        allow_add: true
        min: 1
        i18n: true
        fields:
          - name: icon
            label: Иконка
            widget: string
            i18n: true
            required: false
          - name: title
            label: Название
            widget: string
            i18n: true
  - name: settings
    label: Настройки
    files:
      - name: siteconfig
        label: Настройки веб-сайта
        file: siteconfig.json
        fields:
          - label: Название сайта
            name: name
            widget: string
            hint: Отображается в шапке.
            default: yarkov.tech
          - label: Автор веб-сайта
            name: author
            widget: string
            hint: Отображается в подвале.
          - label: Глобальный заголовок
            name: globalTitle
            widget: string
            hint: Отображется во вкладке браузера.
          - label: В разработке
            name: isSiteUnderConstruction
            widget: boolean
            required: false
            default: false
            hint: Отображает баннер на всех старницах о том, что веб-сайт находится в
              разработке
          - label: Счетчик Яндекс.Метрики
            name: ymCounter
            widget: number
            hint: "Например: 90034656"
            required: false
          - label: Статьи
            name: articles
            widget: object
            fields:
              - name: recentLimit
                label: Лимит на отображение
                widget: number
                hint: Кол-во публикаций на гл.странице
                default: 5
          - label: Контакты
            name: contacts
            widget: object
            required: false
            fields:
              - label: Telegram
                name: telegram
                widget: string
                required: false
              - label: Почта
                name: email
                widget: string
                required: false
              - label: Github
                name: github
                widget: string
                required: false
